package com.qth.dao;

import com.qth.model.Residentialarea;

import java.util.List;

public interface ResidentialareaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Residentialarea
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Residentialarea
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    int insert(Residentialarea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Residentialarea
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    Residentialarea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Residentialarea
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    List<Residentialarea> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Residentialarea
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    int updateByPrimaryKey(Residentialarea record);

    List<Residentialarea> selectDataTable(Residentialarea Residentialarea);

    int selectDataTableCount(Residentialarea Residentialarea);
}