package com.qth.dao;

import com.qth.model.Street;
import java.util.List;

public interface StreetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    int insert(Street record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    Street selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    List<Street> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table street
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    int updateByPrimaryKey(Street record);

    List<Street> selectDataTable(Street street);

    int selectDataTableCount(Street street);
}