package com.qth.model;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_person_name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private String legalPersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.legal_person_license
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private String legalPersonLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.nature
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private Integer nature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_person_name
     *
     * @return the value of company.legal_person_name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public String getLegalPersonName() {
        return legalPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_person_name
     *
     * @param legalPersonName the value for company.legal_person_name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setLegalPersonName(String legalPersonName) {
        this.legalPersonName = legalPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.legal_person_license
     *
     * @return the value of company.legal_person_license
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public String getLegalPersonLicense() {
        return legalPersonLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.legal_person_license
     *
     * @param legalPersonLicense the value for company.legal_person_license
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setLegalPersonLicense(String legalPersonLicense) {
        this.legalPersonLicense = legalPersonLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.nature
     *
     * @return the value of company.nature
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public Integer getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.nature
     *
     * @param nature the value for company.nature
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setNature(Integer nature) {
        this.nature = nature;
    }
}