package com.qth.model;

import com.qth.util.DataTableReqWrapper;

public class Region extends DataTableReqWrapper{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.id
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column region.name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.id
     *
     * @return the value of region.id
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.id
     *
     * @param id the value for region.id
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column region.name
     *
     * @return the value of region.name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column region.name
     *
     * @param name the value for region.name
     *
     * @mbg.generated Fri Apr 13 16:10:18 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}